/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import java.sql.Date;
import model.Connector;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class InputKetResponden extends javax.swing.JFrame {
    private InputKetKuesioner inputKetKuesioner;
    private EntryData entryData;
    private String noResponden;
    private boolean isEditMode = false;
    
    /**
     * Creates new form DataView
     */
    public InputKetResponden(InputKetKuesioner inputKetKuesioner, EntryData entryData, String noResponden) {
        this.inputKetKuesioner = inputKetKuesioner;
        this.entryData = entryData;
        this.noResponden = noResponden;
        this.isEditMode = noResponden != null && !noResponden.trim().isEmpty(); 
        initComponents();
        if (isEditMode) {
            getValueField();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonJenisKelamin = new javax.swing.ButtonGroup();
        button13 = new javax.swing.ButtonGroup();
        button15 = new javax.swing.ButtonGroup();
        Right = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        Right.setBackground(new java.awt.Color(0, 151, 178));
        Right.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("-Amir  -Namira  -Juan  -Shinta");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Survei Kebutuhan Data");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Politeknik Statistika STIS");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("2023/2024");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bpsicon.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kuesioner");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Kelompok 7");

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10))
                .addGap(0, 62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(75, 75, 75))
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(40, 40, 40)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(0, 116, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 151, 178));
        jLabel1.setText("BLOK 1. Keterangan Responden");

        homeButton.setBackground(new java.awt.Color(0, 151, 178));
        homeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        simpanButton.setBackground(new java.awt.Color(0, 151, 178));
        simpanButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        simpanButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tahun Lahir");

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Email");

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("No. Handphone");

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Jenis Kelamin");

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Pendidikan Tertinggi ");

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("yang Ditamatkan");

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Pekerjaan Utama");

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nama Instansi/Institusi");

        jTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelajar/Mahasiswa", "Peneliti/Dosen", "PNS/TNI/Polri", "Pegawai BUMN/BUMD", "Pegawai Swasta", "Wiraswasta", "Lainnya" }));
        jComboBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤ SLTA/Sederajat", "D1/D2/D3", "D4/S1", "S2", "S3", " " }));
        jComboBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));

        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));

        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));

        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Kategori Instansi/Institusi");

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Pemanfaatan Utama Hasil ");

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Kunjungan dan/atau Akses Layanan ");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lembaga Pendidikan & Penelitian Dalam Negeri", "Lembaga Pendidikan & Penelitian Luar Negeri", "Kementerian & Lembaga Pemerintah", "Lembaga Internasional", "Media Massa", "Pemerintahan Daerah", "Perbankan", "BUMN/BUMD", "Swasta Lainnya", "Lainnya", " " }));
        jComboBox4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tugas Sekolah/Tugas Kuliah", "Pemerintahan", "Komersial", "Penelitian", "Lainnya" }));
        jComboBox5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        buttonJenisKelamin.add(jRadioButton5);
        jRadioButton5.setText("Perempuan");
        jRadioButton5.setBorder(null);
        jRadioButton5.setBorderPainted(true);

        buttonJenisKelamin.add(jRadioButton7);
        jRadioButton7.setText("Laki -Laki");
        jRadioButton7.setBorder(null);
        jRadioButton7.setBorderPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21)
                            .addComponent(jLabel15))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jTextField6))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jComboBox3.getAccessibleContext().setAccessibleName("");

        jLabel22.setBackground(new java.awt.Color(102, 102, 102));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Jenis Layanan yang Digunakan");

        jLabel23.setBackground(new java.awt.Color(102, 102, 102));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Fasilitas yang Digunakan Untuk");

        jLabel24.setBackground(new java.awt.Color(102, 102, 102));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("memperoleh layanan BPS");

        jLabel25.setBackground(new java.awt.Color(102, 102, 102));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Apakah Pernah Melakukan Pengaduan ");

        jLabel27.setBackground(new java.awt.Color(102, 102, 102));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Rujukan Utama");

        button13.add(jRadioButton2);
        jRadioButton2.setText("Ya");
        jRadioButton2.setBorder(null);
        jRadioButton2.setBorderPainted(true);

        button13.add(jRadioButton3);
        jRadioButton3.setText("Tidak");
        jRadioButton3.setBorder(null);
        jRadioButton3.setBorderPainted(true);

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Apakah Data BPS digunakan ");

        jLabel28.setBackground(new java.awt.Color(102, 102, 102));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("terkait Pelayanan Statistik Terpadu");

        jCheckBox1.setText("Perpustakaan");
        jCheckBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jCheckBox1.setBorderPainted(true);
        jCheckBox1.setBorderPaintedFlat(true);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Pembelian Publikasi BPS");
        jCheckBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jCheckBox2.setBorderPainted(true);
        jCheckBox2.setBorderPaintedFlat(true);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Pembelian Data Mikro/Peta Wilayah Kerja Statistik");
        jCheckBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jCheckBox3.setBorderPainted(true);
        jCheckBox3.setBorderPaintedFlat(true);

        jCheckBox4.setText("Akses Produk Statistik Pada Website BPS");
        jCheckBox4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jCheckBox4.setBorderPainted(true);
        jCheckBox4.setBorderPaintedFlat(true);

        jCheckBox5.setText("Rekomendasi Kegiatan Statistik");
        jCheckBox5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jCheckBox5.setBorderPainted(true);
        jCheckBox5.setBorderPaintedFlat(true);

        jCheckBox6.setText("Konsultasi Statistik");
        jCheckBox6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jCheckBox6.setBorderPainted(true);
        jCheckBox6.setBorderPaintedFlat(true);
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setText("Datang Langsung ke Unit Pelayanan Statistik terpadu(PST)");
        jCheckBox7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jCheckBox7.setBorderPainted(true);
        jCheckBox7.setBorderPaintedFlat(true);

        jCheckBox8.setText("Aplikasi Pelayanan Statistik Terpadu Online(pst.bps.go.id)");
        jCheckBox8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jCheckBox8.setBorderPainted(true);
        jCheckBox8.setBorderPaintedFlat(true);
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("Website BPS(bps.go.id)");
        jCheckBox9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jCheckBox9.setBorderPainted(true);
        jCheckBox9.setBorderPaintedFlat(true);

        jCheckBox10.setText("Aplikasi AllStats BPS(berbasis android dan ios)");
        jCheckBox10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jCheckBox10.setBorderPainted(true);
        jCheckBox10.setBorderPaintedFlat(true);

        jCheckBox11.setText("Lainnya");
        jCheckBox11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        jCheckBox11.setBorderPainted(true);
        jCheckBox11.setBorderPaintedFlat(true);

        button15.add(jRadioButton8);
        jRadioButton8.setText("Ya");
        jRadioButton8.setBorder(null);
        jRadioButton8.setBorderPainted(true);

        button15.add(jRadioButton9);
        jRadioButton9.setText("Tidak");
        jRadioButton9.setBorder(null);
        jRadioButton9.setBorderPainted(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel28))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26))
                        .addGap(161, 161, 161)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                .addComponent(jCheckBox7)
                                .addComponent(jCheckBox8, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                .addComponent(jCheckBox9, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                .addComponent(jCheckBox10, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Right, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        new MenuView().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        if (isEditMode) {
            updateData();
            new MenuView().setVisible(true);
            dispose();
        } else {
            insertData();
            new MenuView().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_simpanButtonActionPerformed
    
    private void updateData() {
        if (noResponden != null && !noResponden.trim().isEmpty()) {
            String namaPencacah = inputKetKuesioner.getNamaPencacah();
            String namaPemeriksa = inputKetKuesioner.getNamaPemeriksa();
            java.util.Date tanggalInputUtil = inputKetKuesioner.getTanggalInput();

            if (tanggalInputUtil != null) {
                java.sql.Date tanggalInput = new java.sql.Date(tanggalInputUtil.getTime());
                Connector connector = new Connector();
                try (Connection connection = connector.getConnection()) {
                    String sqlUpdate = "UPDATE keterangan_pencacah SET nama_pencacah = ?, nama_pemeriksa = ?, tanggal = ? WHERE no_responden = ?";
                    try (PreparedStatement pstmtUpdate = connection.prepareStatement(sqlUpdate)) {
                        pstmtUpdate.setString(1, namaPencacah);
                        pstmtUpdate.setString(2, namaPemeriksa);
                        pstmtUpdate.setDate(3, tanggalInput);
                        pstmtUpdate.setString(4, noResponden);
                        pstmtUpdate.executeUpdate();
                    }
                    updateRespondenData(connection);
                    JOptionPane.showMessageDialog(this, "Data Keterangan Kuesioner Berhasil Diupdate!");
                    entryData.loadTableData();
                    clearForm();
                } catch (SQLException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Gagal menyimpan data", "Gagal", JOptionPane.ERROR_MESSAGE);
                } finally {
                    connector.closeConnection();
                }
            }
        }
    }
    
    private void insertData() {
        String namaPencacah = inputKetKuesioner.getNamaPencacah();
        String namaPemeriksa = inputKetKuesioner.getNamaPemeriksa();
        String noResponden = inputKetKuesioner.getNoResponden();
        java.util.Date tanggalInputUtil = inputKetKuesioner.getTanggalInput();
        String nama = jTextField1.getText();
        int tahunLahir = Integer.parseInt(jTextField4.getText());
        String email = jTextField5.getText();
        String noHP = jTextField7.getText();
        String jenisKelamin = jRadioButton7.isSelected() ? "Laki-Laki" : "Perempuan";
        String pendidikan = (String) jComboBox2.getSelectedItem();
        String pekerjaan = (String) jComboBox3.getSelectedItem();
        String instansi = jTextField6.getText();
        String katInstansi = (String) jComboBox4.getSelectedItem();
        String pemanfaatan = (String) jComboBox5.getSelectedItem();
        ArrayList<String> jenisLayananList = new ArrayList<>();
        if (jCheckBox1.isSelected()) jenisLayananList.add("Perpustakaan");
        if (jCheckBox2.isSelected()) jenisLayananList.add("Pembelian Publikasi BPS");
        if (jCheckBox3.isSelected()) jenisLayananList.add("Pembelian Data Mikro/Peta Wilayah Kerja Statistik");
        if (jCheckBox4.isSelected()) jenisLayananList.add("Akses Produk Statistik pada Website BPS");
        if (jCheckBox6.isSelected()) jenisLayananList.add("Konsultasi Statistik");
        if (jCheckBox5.isSelected()) jenisLayananList.add("Rekomendasi Kegiatan Statistik");
        String jenisLayanan = String.join(",", jenisLayananList);
        ArrayList<String> fasilitasList = new ArrayList<>();
        if (jCheckBox7.isSelected()) fasilitasList.add("Datang Langsung ke Unit Pelayanan Statistik terpadu(PST)");
        if (jCheckBox8.isSelected()) fasilitasList.add("Aplikasi Pelayanan Statistik Terpadu Online(pst.bps.go.id)");
        if (jCheckBox9.isSelected()) fasilitasList.add("Website BPS(bps.go.id)");
        if (jCheckBox10.isSelected()) fasilitasList.add("Aplikasi AllStats BPS(berbasis android dan ios)");
        if (jCheckBox11.isSelected()) fasilitasList.add("Lainnya");
        String fasilitas = String.join(",", fasilitasList);
        String rujukanUtama = jRadioButton8.isSelected() ? "Ya" : "Tidak";
        String pengaduan = jRadioButton2.isSelected() ? "Ya" : "Tidak";

        if (tanggalInputUtil != null) {
            java.sql.Date tanggalInput = new java.sql.Date(tanggalInputUtil.getTime());
            Connector connector = new Connector();
            try (Connection connection = connector.getConnection()) {
                String sqlPencacah = "INSERT INTO keterangan_pencacah (no_responden, nama_pemeriksa, nama_pencacah, tanggal) VALUES (?, ?, ?, ?)";
                try (PreparedStatement pstmtPencacah = connection.prepareStatement(sqlPencacah)) {
                    pstmtPencacah.setString(1, noResponden);
                    pstmtPencacah.setString(2, namaPemeriksa);
                    pstmtPencacah.setString(3, namaPencacah);
                    pstmtPencacah.setDate(4, tanggalInput);
                    pstmtPencacah.executeUpdate();
                }

                String sqlResponden = "INSERT INTO keterangan_responden (nama, tahun_lahir, email, no_hp, jenis_kelamin, pendidikan_tertinggi, pekerjaan, instansi, kat_instansi, pemanfaatan, jenis_layanan, fasilitas, rujukan_utama, pengaduan, no_responden) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                try (PreparedStatement pstmtResponden = connection.prepareStatement(sqlResponden)) {
                    pstmtResponden.setString(1, nama);
                    pstmtResponden.setInt(2, tahunLahir);
                    pstmtResponden.setString(3, email);
                    pstmtResponden.setString(4, noHP);
                    pstmtResponden.setString(5, jenisKelamin);
                    pstmtResponden.setString(6, pendidikan);
                    pstmtResponden.setString(7, pekerjaan);
                    pstmtResponden.setString(8, instansi);
                    pstmtResponden.setString(9, katInstansi);
                    pstmtResponden.setString(10, pemanfaatan);
                    pstmtResponden.setString(11, jenisLayanan);
                    pstmtResponden.setString(12, fasilitas);
                    pstmtResponden.setString(13, rujukanUtama);
                    pstmtResponden.setString(14, pengaduan);
                    pstmtResponden.setString(15, noResponden);
                    pstmtResponden.executeUpdate();
                }
                JOptionPane.showMessageDialog(this, "Data Berhasil Diinput.");
                entryData.loadTableData();
                inputKetKuesioner.clearForm();
                clearForm();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data", "Gagal", JOptionPane.ERROR_MESSAGE);
            } finally {
                connector.closeConnection();
            }
        }
    }
    
    private void updateRespondenData(Connection connection) throws SQLException {
        String nama = jTextField1.getText();
        int tahunLahir = Integer.parseInt(jTextField4.getText());
        String email = jTextField5.getText();
        String noHP = jTextField7.getText();
        String jenisKelamin = jRadioButton7.isSelected() ? "Laki-Laki" : "Perempuan";
        String pendidikan = (String) jComboBox2.getSelectedItem();
        String pekerjaan = (String) jComboBox3.getSelectedItem();
        String instansi = jTextField6.getText();
        String katInstansi = (String) jComboBox4.getSelectedItem();
        String pemanfaatan = (String) jComboBox5.getSelectedItem();
        ArrayList<String> jenisLayananList = new ArrayList<>();
        if (jCheckBox1.isSelected()) jenisLayananList.add("Perpustakaan");
        if (jCheckBox2.isSelected()) jenisLayananList.add("Pembelian Publikasi BPS");
        if (jCheckBox3.isSelected()) jenisLayananList.add("Pembelian Data Mikro/Peta Wilayah Kerja Statistik");
        if (jCheckBox4.isSelected()) jenisLayananList.add("Akses Produk Statistik pada Website BPS");
        if (jCheckBox6.isSelected()) jenisLayananList.add("Konsultasi Statistik");
        if (jCheckBox5.isSelected()) jenisLayananList.add("Rekomendasi Kegiatan Statistik");
        String jenisLayanan = String.join(",", jenisLayananList);
        ArrayList<String> fasilitasList = new ArrayList<>();
        if (jCheckBox7.isSelected()) fasilitasList.add("Datang Langsung ke Unit Pelayanan Statistik terpadu(PST)");
        if (jCheckBox8.isSelected()) fasilitasList.add("Aplikasi Pelayanan Statistik Terpadu Online(pst.bps.go.id)");
        if (jCheckBox9.isSelected()) fasilitasList.add("Website BPS(bps.go.id)");
        if (jCheckBox10.isSelected()) fasilitasList.add("Aplikasi AllStats BPS(berbasis android dan ios)");
        if (jCheckBox11.isSelected()) fasilitasList.add("Lainnya");
        String fasilitas = String.join(",", fasilitasList);
        String rujukanUtama = jRadioButton8.isSelected() ? "Ya" : "Tidak";
        String pengaduan = jRadioButton2.isSelected() ? "Ya" : "Tidak";

        String sqlResponden = "UPDATE keterangan_responden SET nama = ?, tahun_lahir = ?, email = ?, no_hp = ?, jenis_kelamin = ?, pendidikan_tertinggi = ?, pekerjaan = ?, instansi = ?, kat_instansi = ?, pemanfaatan = ?, jenis_layanan = ?, fasilitas = ?, rujukan_utama = ?, pengaduan = ? WHERE no_responden = ?";
        try (PreparedStatement pstmtResponden = connection.prepareStatement(sqlResponden)) {
            pstmtResponden.setString(1, nama);
            pstmtResponden.setInt(2, tahunLahir);
            pstmtResponden.setString(3, email);
            pstmtResponden.setString(4, noHP);
            pstmtResponden.setString(5, jenisKelamin);
            pstmtResponden.setString(6, pendidikan);
            pstmtResponden.setString(7, pekerjaan);
            pstmtResponden.setString(8, instansi);
            pstmtResponden.setString(9, katInstansi);
            pstmtResponden.setString(10, pemanfaatan);
            pstmtResponden.setString(11, jenisLayanan);
            pstmtResponden.setString(12, fasilitas);
            pstmtResponden.setString(13, rujukanUtama);
            pstmtResponden.setString(14, pengaduan);
            pstmtResponden.setString(15, noResponden);
            pstmtResponden.executeUpdate();
        }
    }
    
    
    private void simpanButtonCOBA() {
        // CEK APAKAH NO_RESPONDEN SUDAH ADA
        // SUDAH: UPDATE KET_PENCACAH, DISABLE FIELD KET_RESPONDEN
        // BELUM: INSERT KE KET_PENCACAH SEKALIGUS KET_RESPONDEN
        Connector connector = new Connector();
        try (Connection connection = connector.getConnection()) {
            // dapatkan nomor responden
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    public void getValueField() {
        Connector connector = new Connector();
        try (Connection connection = connector.getConnection()) {
            String sql = "SELECT * FROM keterangan_responden WHERE no_responden = ?";
            try (PreparedStatement pstmt = connection.prepareStatement(sql)) {
                pstmt.setString(1, noResponden);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        jTextField1.setText(rs.getString("nama"));
                        jTextField4.setText(rs.getString("tahun_lahir"));
                        jTextField5.setText(rs.getString("email"));
                        jTextField7.setText(rs.getString("no_hp"));
                        if ("Laki-Laki".equals(rs.getString("jenis_kelamin"))) {
                            jRadioButton7.setSelected(true);
                        } else {
                            jRadioButton5.setSelected(true);
                        }
                        jComboBox2.setSelectedItem(rs.getString("pendidikan_tertinggi"));
                        jComboBox3.setSelectedItem(rs.getString("pekerjaan"));
                        jTextField6.setText(rs.getString("instansi"));
                        jComboBox4.setSelectedItem(rs.getString("kat_instansi"));
                        jComboBox5.setSelectedItem(rs.getString("pemanfaatan"));
                        String[] jenisLayananArray = rs.getString("jenis_layanan").split(",");
                        for (String layanan : jenisLayananArray) {
                            switch (layanan) {
                                case "Perpustakaan":
                                    jCheckBox1.setSelected(true);
                                    break;
                                case "Pembelian Publikasi BPS":
                                    jCheckBox2.setSelected(true);
                                    break;
                                case "Pembelian Data Mikro/Peta Wilayah Kerja Statistik":
                                    jCheckBox3.setSelected(true);
                                    break;
                                case "Akses Produk Statistik pada Website BPS":
                                    jCheckBox4.setSelected(true);
                                    break;
                                case "Konsultasi Statistik":
                                    jCheckBox6.setSelected(true);
                                    break;
                                case "Rekomendasi Kegiatan Statistik":
                                    jCheckBox5.setSelected(true);
                                    break;
                            }
                        }
                        String[] fasilitasArray = rs.getString("fasilitas").split(",");
                        for (String fasilitas : fasilitasArray) {
                            switch (fasilitas) {
                                case "Datang Langsung ke Unit Pelayanan Statistik terpadu(PST)":
                                    jCheckBox7.setSelected(true);
                                    break;
                                case "Aplikasi Pelayanan Statistik Terpadu Online(pst.bps.go.id)":
                                    jCheckBox8.setSelected(true);
                                    break;
                                case "Website BPS(bps.go.id)":
                                    jCheckBox9.setSelected(true);
                                    break;
                                case "Aplikasi AllStats BPS(berbasis android dan ios)":
                                    jCheckBox10.setSelected(true);
                                    break;
                                case "Lainnya":
                                    jCheckBox11.setSelected(true);
                                    break;
                            }
                        }
                        if ("Ya".equals(rs.getString("rujukan_utama"))) {
                            jRadioButton8.setSelected(true);
                        } else {
                            jRadioButton9.setSelected(true);
                        }
                        if ("Ya".equals(rs.getString("pengaduan"))) {
                            jRadioButton2.setSelected(true);
                        } else {
                            jRadioButton3.setSelected(true);
                        }
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal mengambil data", "Gagal", JOptionPane.ERROR_MESSAGE);
        } finally {
            connector.closeConnection();
        }
    }
    
    private void disableAllFields() {
        jTextField1.setEnabled(false); // nama
        jTextField4.setEnabled(false); // tahunLahir
        jTextField5.setEnabled(false); // email
        jTextField7.setEnabled(false); // noHP
        jRadioButton7.setEnabled(false); // jenisKelamin Laki-Laki
        jRadioButton5.setEnabled(false); // jenisKelamin Perempuan
        jComboBox2.setEnabled(false); // pendidikan
        jComboBox3.setEnabled(false); // pekerjaan
        jTextField6.setEnabled(false); // instansi
        jComboBox4.setEnabled(false); // katInstansi
        jComboBox5.setEnabled(false); // pemanfaatan
        jCheckBox1.setEnabled(false); // Perpustakaan
        jCheckBox2.setEnabled(false); // Pembelian Publikasi BPS
        jCheckBox3.setEnabled(false); // Pembelian Data Mikro/Peta Wilayah Kerja Statistik
        jCheckBox4.setEnabled(false); // Akses Produk Statistik pada Website BPS
        jCheckBox6.setEnabled(false); // Konsultasi Statistik
        jCheckBox5.setEnabled(false); // Rekomendasi Kegiatan Statistik
        jCheckBox7.setEnabled(false); // Datang Langsung ke Unit Pelayanan Statistik terpadu(PST)
        jCheckBox8.setEnabled(false); // Aplikasi Pelayanan Statistik Terpadu Online(pst.bps.go.id)
        jCheckBox9.setEnabled(false); // Website BPS(bps.go.id)
        jCheckBox10.setEnabled(false); // Aplikasi AllStats BPS(berbasis android dan ios)
        jCheckBox11.setEnabled(false); // Lainnya
        jRadioButton8.setEnabled(false); // rujukanUtama Ya
        jRadioButton9.setEnabled(false); // rujukanUtama Tidak
        jRadioButton2.setEnabled(false); // pengaduan Ya
        jRadioButton3.setEnabled(false); // pengaduan Tidak
    }
    
    
    private void clearForm() {
        jTextField1.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField7.setText("");
        buttonJenisKelamin.clearSelection();
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jTextField6.setText("");
        jComboBox4.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jCheckBox10.setSelected(false);
        jCheckBox11.setSelected(false);
        button15.clearSelection();
        button13.clearSelection();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataView().setVisible(true);
            }
        });
    }
    
    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Right;
    private javax.swing.ButtonGroup button13;
    private javax.swing.ButtonGroup button15;
    private javax.swing.ButtonGroup buttonJenisKelamin;
    private javax.swing.JButton homeButton;
    public javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JCheckBox jCheckBox10;
    public javax.swing.JCheckBox jCheckBox11;
    public javax.swing.JCheckBox jCheckBox2;
    public javax.swing.JCheckBox jCheckBox3;
    public javax.swing.JCheckBox jCheckBox4;
    public javax.swing.JCheckBox jCheckBox5;
    public javax.swing.JCheckBox jCheckBox6;
    public javax.swing.JCheckBox jCheckBox7;
    public javax.swing.JCheckBox jCheckBox8;
    public javax.swing.JCheckBox jCheckBox9;
    public javax.swing.JComboBox<String> jComboBox2;
    public javax.swing.JComboBox<String> jComboBox3;
    public javax.swing.JComboBox<String> jComboBox4;
    public javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JRadioButton jRadioButton3;
    public javax.swing.JRadioButton jRadioButton5;
    public javax.swing.JRadioButton jRadioButton7;
    public javax.swing.JRadioButton jRadioButton8;
    public javax.swing.JRadioButton jRadioButton9;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    private javax.swing.JButton simpanButton;
    // End of variables declaration//GEN-END:variables
}
