/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.*;
import model.Connector;

/**
 *
 * @author shinta
 */
public class KetKuesioner extends javax.swing.JFrame {
    private String noResponden;
    private JCheckBox[] jenisLayananCheckBoxes;
    private JCheckBox[] fasilitasCheckBoxes;

    /**
     * Creates new form KetKuesioner
     */
    public KetKuesioner(String nomorResponden) {
        initComponents();
        this.noResponden = nomorResponden;
        
        jenisLayananCheckBoxes = new JCheckBox[] {
            perpustakaanCheckBox,
            publikasiCheckBox,
            rekomendasiCheckBox,
            dataMikroCheckBox,
            aksesProdukCheckBox,
            konsultasiCheckBox
        };
        
        fasilitasCheckBoxes = new JCheckBox[] {
            datangLangsungCheckBox,
            aplikasiPSTCheckBox,
            websiteCheckBox,
            allStatsCheckBox,
            lainnyaCheckBox
        };
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelaminButtonGroup = new javax.swing.ButtonGroup();
        rujukanButtonGroup = new javax.swing.ButtonGroup();
        pengaduanButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        instansiField = new javax.swing.JTextField();
        pekerjaanComboBox = new javax.swing.JComboBox<>();
        pendidikanComboBox = new javax.swing.JComboBox<>();
        noHpField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        tahunLahirField = new javax.swing.JTextField();
        namaField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        katInstansiComboBox = new javax.swing.JComboBox<>();
        pemanfaatanComboBox = new javax.swing.JComboBox<>();
        perempuanRadioButton = new javax.swing.JRadioButton();
        lakiRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        pengaduanYa = new javax.swing.JRadioButton();
        pengaduanTidak = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        rujukanUtamaYa = new javax.swing.JRadioButton();
        rujukanUtamaTidak = new javax.swing.JRadioButton();
        perpustakaanCheckBox = new javax.swing.JCheckBox();
        publikasiCheckBox = new javax.swing.JCheckBox();
        dataMikroCheckBox = new javax.swing.JCheckBox();
        aksesProdukCheckBox = new javax.swing.JCheckBox();
        rekomendasiCheckBox = new javax.swing.JCheckBox();
        konsultasiCheckBox = new javax.swing.JCheckBox();
        datangLangsungCheckBox = new javax.swing.JCheckBox();
        aplikasiPSTCheckBox = new javax.swing.JCheckBox();
        websiteCheckBox = new javax.swing.JCheckBox();
        allStatsCheckBox = new javax.swing.JCheckBox();
        lainnyaCheckBox = new javax.swing.JCheckBox();
        Right1 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 151, 178));
        jLabel1.setText("BLOK 1. Keterangan Responden");
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 48));

        homeButton.setBackground(new java.awt.Color(0, 151, 178));
        homeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tahun Lahir");
        jLabel3.setPreferredSize(new java.awt.Dimension(72, 30));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Email");

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("No. Handphone");

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Jenis Kelamin");

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Pendidikan Tertinggi ");

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("yang Ditamatkan");

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Pekerjaan Utama");

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nama Instansi/Institusi");

        instansiField.setEditable(false);
        instansiField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        instansiField.setFocusable(false);

        pekerjaanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelajar/Mahasiswa", "Peneliti/Dosen", "PNS/TNI/Polri", "Pegawai BUMN/BUMD", "Pegawai Swasta", "Wiraswasta", "Lainnya" }));
        pekerjaanComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        pekerjaanComboBox.setEnabled(false);

        pendidikanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤ SLTA/Sederajat", "D1/D2/D3", "D4/S1", "S2", "S3", " " }));
        pendidikanComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        pendidikanComboBox.setEnabled(false);

        noHpField.setEditable(false);
        noHpField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        noHpField.setFocusable(false);

        emailField.setEditable(false);
        emailField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        emailField.setFocusable(false);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        tahunLahirField.setEditable(false);
        tahunLahirField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        tahunLahirField.setFocusable(false);

        namaField.setEditable(false);
        namaField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        namaField.setFocusable(false);

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Kategori Instansi/Institusi");

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Pemanfaatan Utama Hasil");

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Kunjungan dan/atau Akses Layanan ");

        katInstansiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lembaga Pendidikan & Penelitian Dalam Negeri", "Lembaga Pendidikan & Penelitian Luar Negeri", "Kementerian & Lembaga Pemerintah", "Lembaga Internasional", "Media Massa", "Pemerintahan Daerah", "Perbankan", "BUMN/BUMD", "Swasta Lainnya", "Lainnya", " " }));
        katInstansiComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        katInstansiComboBox.setEnabled(false);
        katInstansiComboBox.setFocusable(false);

        pemanfaatanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tugas Sekolah/Tugas Kuliah", "Pemerintahan", "Komersial", "Penelitian", "Lainnya" }));
        pemanfaatanComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        pemanfaatanComboBox.setEnabled(false);
        pemanfaatanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemanfaatanComboBoxActionPerformed(evt);
            }
        });

        jenisKelaminButtonGroup.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.setBorder(null);
        perempuanRadioButton.setBorderPainted(true);
        perempuanRadioButton.setEnabled(false);
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });

        jenisKelaminButtonGroup.add(lakiRadioButton);
        lakiRadioButton.setText("Laki-Laki");
        lakiRadioButton.setBorder(null);
        lakiRadioButton.setBorderPainted(true);
        lakiRadioButton.setEnabled(false);
        lakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(tahunLahirField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(noHpField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pendidikanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lakiRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(perempuanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pekerjaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(instansiField))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(katInstansiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pemanfaatanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tahunLahirField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noHpField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(perempuanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lakiRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendidikanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pekerjaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instansiField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(katInstansiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pemanfaatanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(27, 27, 27))
        );

        jLabel22.setBackground(new java.awt.Color(102, 102, 102));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Jenis Layanan yang Digunakan");

        jLabel23.setBackground(new java.awt.Color(102, 102, 102));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Fasilitas yang Digunakan Untuk");

        jLabel24.setBackground(new java.awt.Color(102, 102, 102));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("memperoleh layanan BPS");

        jLabel25.setBackground(new java.awt.Color(102, 102, 102));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Apakah Pernah Melakukan Pengaduan ");

        jLabel27.setBackground(new java.awt.Color(102, 102, 102));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Rujukan Utama");

        pengaduanButtonGroup.add(pengaduanYa);
        pengaduanYa.setText("Ya");
        pengaduanYa.setBorder(null);
        pengaduanYa.setBorderPainted(true);
        pengaduanYa.setEnabled(false);

        pengaduanButtonGroup.add(pengaduanTidak);
        pengaduanTidak.setText("Tidak");
        pengaduanTidak.setBorder(null);
        pengaduanTidak.setBorderPainted(true);
        pengaduanTidak.setEnabled(false);

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Apakah Data BPS digunakan ");

        jLabel28.setBackground(new java.awt.Color(102, 102, 102));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("terkait Pelayanan Statistik Terpadu");

        rujukanButtonGroup.add(rujukanUtamaYa);
        rujukanUtamaYa.setText("Ya");
        rujukanUtamaYa.setBorder(null);
        rujukanUtamaYa.setBorderPainted(true);
        rujukanUtamaYa.setEnabled(false);

        rujukanButtonGroup.add(rujukanUtamaTidak);
        rujukanUtamaTidak.setText("Tidak");
        rujukanUtamaTidak.setBorder(null);
        rujukanUtamaTidak.setBorderPainted(true);

        perpustakaanCheckBox.setText("Perpustakaan");
        perpustakaanCheckBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        perpustakaanCheckBox.setBorderPainted(true);
        perpustakaanCheckBox.setBorderPaintedFlat(true);
        perpustakaanCheckBox.setEnabled(false);
        perpustakaanCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perpustakaanCheckBoxActionPerformed(evt);
            }
        });

        publikasiCheckBox.setText("Pembelian Publikasi BPS");
        publikasiCheckBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        publikasiCheckBox.setBorderPainted(true);
        publikasiCheckBox.setBorderPaintedFlat(true);
        publikasiCheckBox.setEnabled(false);

        dataMikroCheckBox.setText("Pembelian Data Mikro/Peta Wilayah Kerja Statistik");
        dataMikroCheckBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        dataMikroCheckBox.setBorderPainted(true);
        dataMikroCheckBox.setBorderPaintedFlat(true);
        dataMikroCheckBox.setEnabled(false);

        aksesProdukCheckBox.setText("Akses Produk Statistik Pada Website BPS");
        aksesProdukCheckBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        aksesProdukCheckBox.setBorderPainted(true);
        aksesProdukCheckBox.setBorderPaintedFlat(true);
        aksesProdukCheckBox.setEnabled(false);

        rekomendasiCheckBox.setText("Rekomendasi Kegiatan Statistik");
        rekomendasiCheckBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        rekomendasiCheckBox.setBorderPainted(true);
        rekomendasiCheckBox.setBorderPaintedFlat(true);
        rekomendasiCheckBox.setEnabled(false);

        konsultasiCheckBox.setText("Konsultasi Statistik");
        konsultasiCheckBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        konsultasiCheckBox.setBorderPainted(true);
        konsultasiCheckBox.setBorderPaintedFlat(true);
        konsultasiCheckBox.setEnabled(false);
        konsultasiCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konsultasiCheckBoxActionPerformed(evt);
            }
        });

        datangLangsungCheckBox.setText("Datang Langsung ke Unit Pelayanan Statistik terpadu(PST)");
        datangLangsungCheckBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        datangLangsungCheckBox.setBorderPainted(true);
        datangLangsungCheckBox.setBorderPaintedFlat(true);
        datangLangsungCheckBox.setEnabled(false);

        aplikasiPSTCheckBox.setText("Aplikasi Pelayanan Statistik Terpadu Online(pst.bps.go.id)");
        aplikasiPSTCheckBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        aplikasiPSTCheckBox.setBorderPainted(true);
        aplikasiPSTCheckBox.setBorderPaintedFlat(true);
        aplikasiPSTCheckBox.setEnabled(false);

        websiteCheckBox.setText("Website BPS(bps.go.id)");
        websiteCheckBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        websiteCheckBox.setBorderPainted(true);
        websiteCheckBox.setBorderPaintedFlat(true);
        websiteCheckBox.setEnabled(false);

        allStatsCheckBox.setText("Aplikasi AllStats BPS(berbasis android dan ios)");
        allStatsCheckBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        allStatsCheckBox.setBorderPainted(true);
        allStatsCheckBox.setBorderPaintedFlat(true);
        allStatsCheckBox.setEnabled(false);

        lainnyaCheckBox.setText("Lainnya");
        lainnyaCheckBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 151, 178), 2, true));
        lainnyaCheckBox.setBorderPainted(true);
        lainnyaCheckBox.setBorderPaintedFlat(true);
        lainnyaCheckBox.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rujukanUtamaYa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rujukanUtamaTidak, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pengaduanYa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pengaduanTidak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(publikasiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perpustakaanCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataMikroCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aksesProdukCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(konsultasiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rekomendasiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datangLangsungCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aplikasiPSTCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(websiteCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(allStatsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lainnyaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(perpustakaanCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publikasiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataMikroCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aksesProdukCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(konsultasiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rekomendasiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(datangLangsungCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aplikasiPSTCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(websiteCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allStatsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lainnyaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rujukanUtamaYa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rujukanUtamaTidak, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(pengaduanYa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pengaduanTidak, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        Right1.setBackground(new java.awt.Color(0, 151, 178));
        Right1.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("-Amir  -Namira  -Juan  -Shinta");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Survei Kebutuhan Data");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Politeknik Statistika STIS");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("2023/2024");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bpsicon.png"))); // NOI18N
        jLabel34.setText("jLabel11");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Kuesioner");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Kelompok 7");

        javax.swing.GroupLayout Right1Layout = new javax.swing.GroupLayout(Right1);
        Right1.setLayout(Right1Layout);
        Right1Layout.setHorizontalGroup(
            Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(Right1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right1Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right1Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
            .addGroup(Right1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel30)
                    .addGroup(Right1Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(50, 50, 50)))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addContainerGap())
        );
        Right1Layout.setVerticalGroup(
            Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right1Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jLabel32)
                .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Right1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel29)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel33)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Right1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(Right1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        new MenuView().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void pemanfaatanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemanfaatanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pemanfaatanComboBoxActionPerformed

    private void konsultasiCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konsultasiCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konsultasiCheckBoxActionPerformed

    private void lakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiRadioButtonActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void perpustakaanCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perpustakaanCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perpustakaanCheckBoxActionPerformed

    private void loadData() {
        Connector connector = new Connector();
        String query = "SELECT * FROM keterangan_responden WHERE no_responden = ?";

        try (PreparedStatement pstmt = connector.koneksi.prepareStatement(query)) {
            // Set parameter for nomorResponden
            pstmt.setString(1, noResponden);

            // Execute query
            ResultSet rs = pstmt.executeQuery();

            int no = 1;

            while (rs.next()) {
                // Retrieve data from ResultSet
                String nama = rs.getString("nama");
                String tahunLahir = rs.getString("tahun_lahir");
                String email = rs.getString("email");
                String noHp = rs.getString("no_hp");
                String jenisKelamin = rs.getString("jenis_kelamin");
                String pendidikanTertinggi = rs.getString("pendidikan_tertinggi");
                String pekerjaan = rs.getString("pekerjaan");
                String instansi = rs.getString("instansi");
                String katInstansi = rs.getString("kat_instansi");
                String pemanfaatan = rs.getString("pemanfaatan");
                String jenisLayanan = rs.getString("jenis_layanan");
                String fasilitas = rs.getString("fasilitas");
                String rujukanUtama = rs.getString("rujukan_utama");
                String pengaduan = rs.getString("pengaduan");

                SwingUtilities.invokeLater(() -> {
                    namaField.setText(nama);                    
                    tahunLahirField.setText(tahunLahir);
                    emailField.setText(email);
                    noHpField.setText(noHp);
                    
                    // Set radio buttons for rujukanUtama
                    if ("Laki-Laki".equals(jenisKelamin)) {
                        lakiRadioButton.setSelected(true);
                    } else if ("Perempuan".equals(jenisKelamin)) {
                        perempuanRadioButton.setSelected(true);
                    }
                    
                    // Set combo boxes
                    pendidikanComboBox.setSelectedItem(pendidikanTertinggi);
                    pekerjaanComboBox.setSelectedItem(pekerjaan);
                    instansiField.setText(instansi);
                    katInstansiComboBox.setSelectedItem(katInstansi);
                    pemanfaatanComboBox.setSelectedItem(pemanfaatan);

                    // Set text field for instansi
                    instansiField.setText(instansi);

                    // Set checkboxes for jenisLayanan
                    setCheckboxes(jenisLayananCheckBoxes, jenisLayanan);

                    // Set checkboxes for fasilitas
                    setCheckboxes(fasilitasCheckBoxes, fasilitas);

                    // Set radio buttons for rujukanUtama
                    if ("Ya".equals(rujukanUtama)) {
                        rujukanUtamaYa.setSelected(true);
                    } else if ("Tidak".equals(rujukanUtama)) {
                        rujukanUtamaTidak.setSelected(true);
                    }

                    // Set radio buttons for pengaduan
                    if ("Ya".equals(pengaduan)) {
                        pengaduanYa.setSelected(true);
                    } else if ("Tidak".equals(pengaduan)) {
                        pengaduanTidak.setSelected(true);
                    }
                    
                });
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void setCheckboxes(JCheckBox[] checkBoxes, String values) {
        String[] valueArray = values.split(","); // Assuming the values are comma-separated
        for (JCheckBox checkBox : checkBoxes) {
            for (String value : valueArray) {
                if (checkBox.getText().equalsIgnoreCase(value.trim())) {
                    checkBox.setSelected(true);
                    break;
                }
            }
            checkBox.setEnabled(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KetKuesioner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KetKuesioner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KetKuesioner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KetKuesioner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Right1;
    private javax.swing.JCheckBox aksesProdukCheckBox;
    private javax.swing.JCheckBox allStatsCheckBox;
    private javax.swing.JCheckBox aplikasiPSTCheckBox;
    private javax.swing.JCheckBox dataMikroCheckBox;
    private javax.swing.JCheckBox datangLangsungCheckBox;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton homeButton;
    private javax.swing.JTextField instansiField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup jenisKelaminButtonGroup;
    private javax.swing.JComboBox<String> katInstansiComboBox;
    private javax.swing.JCheckBox konsultasiCheckBox;
    private javax.swing.JCheckBox lainnyaCheckBox;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField noHpField;
    private javax.swing.JComboBox<String> pekerjaanComboBox;
    private javax.swing.JComboBox<String> pemanfaatanComboBox;
    private javax.swing.JComboBox<String> pendidikanComboBox;
    private javax.swing.ButtonGroup pengaduanButtonGroup;
    private javax.swing.JRadioButton pengaduanTidak;
    private javax.swing.JRadioButton pengaduanYa;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JCheckBox perpustakaanCheckBox;
    private javax.swing.JCheckBox publikasiCheckBox;
    private javax.swing.JCheckBox rekomendasiCheckBox;
    private javax.swing.ButtonGroup rujukanButtonGroup;
    private javax.swing.JRadioButton rujukanUtamaTidak;
    private javax.swing.JRadioButton rujukanUtamaYa;
    private javax.swing.JTextField tahunLahirField;
    private javax.swing.JCheckBox websiteCheckBox;
    // End of variables declaration//GEN-END:variables
}
